Jkantor/notices
openedx/frontend-app-learner-dashboard pull request #134
Opened 2023-04-17 14:51 UTC by jansenk

- Add notices to learner home.

Testing instructions:
 - set up https://github.com/edx/platform-plugin-notices for running locally
 - create a notice (I would suggest looking at the read replica and copying the 2u notice, the structure of the model data is a little confusing)
 - Navigate to the learner home. You should be redirected to the notice.

2023-04-17 15:29 UTC, leangseu-edx commented on src/components/NoticesProvider/index.jsx
> +const NoticesProvider = ({ children }) => {
Can you rename this to something else? Providers generally reserve for `React.Context`. It might cause confusing in the future.

2023-04-17 15:31 UTC, leangseu-edx requested changes
Just name change for `NoticesProvider`. Everything else look good.

🥇  I like the decision to keep everything inside a single folder. I wouldn't

2023-04-18 13:27 UTC, jansenk commented on src/components/NoticesProvider/index.jsx
> +const NoticesProvider = ({ children }) => {
What would you suggest? This is what it's called in the programs dashboard and the learning mfe

2023-04-18 13:39 UTC, leangseu-edx commented on src/components/NoticesProvider/index.jsx
> +const NoticesProvider = ({ children }) => {
`NoticesWrapper`?

2023-04-19 16:14 UTC, leangseu-edx approved these changes
LGTM 👍

2023-04-19 18:35 UTC, merged