fix(deps): replace edx.org brand dependency with openedx brand (#183)
openedx/frontend-app-learner-dashboard pull request #184
Opened 2023-08-08 09:13 UTC by snglth

@edx/brand-edx.org package is not open source. @edx/brand-openedx is what is used by other MFEs by default.

Similar PRs:
- [Gradebook](https://github.com/openedx/frontend-app-gradebook/pull/327)
- [ORA grading](https://github.com/openedx/frontend-app-ora-grading/pull/200)

2023-08-08 09:13 UTC, openedx-webhooks commented
Thanks for the pull request, @snglth!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-08-15 13:20 UTC, itsjeyd commented
Hi @snglth, thank you for this contribution!

Let us know when the changes are ready for review, please.

2023-08-16 09:53 UTC, snglth commented
Hi @itsjeyd,

Changes are ready for the review.

2023-08-22 14:35 UTC, itsjeyd commented
@snglth Sounds good @snglth, I'll line this PR up for a test run now. Once the build is green we can get the engineering review process started.

2023-09-13 12:34 UTC, itsjeyd commented
Hi @asadazam93, this is ready for engineering review by Infinity.

2023-09-26 06:55 UTC, itsjeyd commented
@mattcarter Friendly ping about getting this PR into Aurora's queue for engineering review.

CC @openedx/content-aurora

2023-10-11 19:51 UTC, mattcarter approved these changes
approved

2023-10-13 08:26 UTC, itsjeyd commented
Thanks a lot @mattcarter!

@snglth Please resolve branch conflicts here, then the changes should be ready for merge.

2023-10-20 15:45 UTC, arbrandes requested changes

2023-10-20 15:45 UTC, arbrandes commented on package.json
> +    "@edx/brand": "npm:@edx/brand-openedx@^1.2.0",
Do you mind making the following change?

```suggestion
    "@edx/brand": "npm:@openedx/brand-openedx@^1.2.2",
```

We're moving the package from `edx` to `openedx`, as per https://github.com/openedx/axim-engineering/issues/23.

2023-10-23 01:23 UTC, snglth commented
Resolved conflicts and picked brand from `openedx` organization as suggested by @arbrandes

2023-10-23 15:53 UTC, arbrandes approved these changes

2023-10-23 18:07 UTC, merged