fix: add development environment variable
openedx/frontend-app-learner-dashboard pull request #214
Opened 2023-10-11 19:39 UTC by httpsmenahassan

Resolves https://github.com/openedx/frontend-app-learner-dashboard/issues/210

2023-10-12 19:18 UTC, arbrandes approved these changes
Great, thanks!

2023-10-12 19:35 UTC, arbrandes requested changes
Just one thing, as commented above.

2023-10-12 19:35 UTC, arbrandes commented on .env.development
> +EXPERIMENT_08_23_VAN_PAINTED_DOOR=true
Actually, mind setting this to `false`?  We don't actually need the experiment to run, just for the variable to be set.

2023-10-13 14:19 UTC, httpsmenahassan commented on .env.development
> +EXPERIMENT_08_23_VAN_PAINTED_DOOR=true
@arbrandes all set! changed to false

2023-10-13 15:04 UTC, arbrandes approved these changes

2023-10-13 20:04 UTC, brian-smith-tcril commented
@arbrandes I just tried this locally with `EXPERIMENT_08_23_VAN_PAINTED_DOOR=false` and I ran into the same `TypeError`

I also got the `TypeError` when changing this line
https://github.com/openedx/frontend-app-learner-dashboard/blob/82ff0d7ddb95e316ef6c0251de49bafebe0b93d9/src/containers/WidgetContainers/AppWrapper/index.jsx#L9
to be
```jsx
if (false) {
```

I'm doing a bit more digging now

2023-10-13 20:08 UTC, brian-smith-tcril commented
I think https://github.com/openedx/frontend-app-learner-dashboard/pull/218 should do the trick

2023-10-16 15:02 UTC, httpsmenahassan commented
@brian-smith-tcril thanks for digging into this, Brian! I'll take a look at your PR

2023-10-16 18:30 UTC, brian-smith-tcril commented
To follow up on this, I tried `EXPERIMENT_08_23_VAN_PAINTED_DOOR=false` again today and no longer could reproduce the error. I set a breakpoint

https://github.com/openedx/frontend-app-learner-dashboard/blob/82ff0d7ddb95e316ef6c0251de49bafebe0b93d9/src/containers/WidgetContainers/AppWrapper/index.jsx#L9

and saw `process.env.EXPERIMENT_08_23_VAN_PAINTED_DOOR` evaluating to `true`

I'm not sure what magic I did on Friday to get strings to parse as bools, but it doesn't seem to be working now (all non-empty strings are being treated as true)

When I set `EXPERIMENT_08_23_VAN_PAINTED_DOOR=''` instead, `process.env.EXPERIMENT_08_23_VAN_PAINTED_DOOR` evaluated to `false` and I got to the same `TypeError`

2023-10-20 13:22 UTC, justinhynes commented
I'll be bringing this PR our next team refinement session for prioritization.

2023-11-13 21:07 UTC, jsnwesson commented
Hey @brian-smith-tcril and @arbrandes, Team Aperture was originally assigned `needs maintainer attention` for both this PR and #218 , but according to Brian's comment above, #218 would make this PR redundant. If that is the case, should we only review #218 (as in only have that PR reviewed by the team responsible for the experiment)?

2023-11-14 15:20 UTC, brian-smith-tcril commented
@jsnwesson I think reviewing #218 first makes sense. If that solution is seen as problematic for some reason then this PR should be merged as a workaround until a better solution is agreed upon.

2023-11-16 11:30 UTC, arbrandes commented
#218 was merged.  Do we still need this?

2023-11-16 15:39 UTC, brian-smith-tcril commented
@arbrandes

> Do we still need this?

nope! #218 should do the trick!

2023-11-16 16:03 UTC, httpsmenahassan commented
Thanks, everyone! I'll go ahead and close this.

2023-11-16 16:03 UTC, closed without merging