Add fallback image for the course card images
openedx/frontend-app-learner-dashboard pull request #324
Opened 2024-04-22 13:54 UTC by hinakhadim

When there is no image for course, then the screen shows alt text with broken image icon. This PR fixes it by adding an error image url. The Error image needs to be added in `edx-platform` with name `no_course_image.png`. This works perfectly with even `tutor-indigo` or any theme you want to set using `tutor`.

### Before:
<img width="955" alt="Screenshot 2024-04-22 at 6 07 58 PM" src="https://github.com/openedx/frontend-app-learner-dashboard/assets/112946189/f312f033-930d-4c9e-97b1-d1a66943a0df">

### After:
If the image exists in theme:

<img width="955" alt="Screenshot 2024-04-22 at 6 44 25 PM" src="https://github.com/openedx/frontend-app-learner-dashboard/assets/112946189/2e792d43-1976-47be-83bd-3e2c574f2589">

If the image with name `no_course_image.png` won't exist, then it will show the alt text with broken image icon. 

### Impact:

1. It will enhance user experience
2. It'll maintain consistency of the course card layout
3. Easy to implement with tutor-indigo theme or any customizable theme. Just need to add image with that name.

2024-04-23 16:43 UTC, justinhynes commented on src/containers/CourseCard/components/CourseCardImage.jsx
> +  const fallbackImageSrc = `${getConfig().LMS_BASE_URL}/theming/asset/images/no_course_image.png`;
Is the `no_course_image.png` asset included by default as part of `edx-platform`? I was trying to check now and I can't find anything in the `master` branch with this name, but maybe I am missing it.

2024-04-23 16:44 UTC, justinhynes commented
Hi @mphilbrick211 -- Is this something that would need product eyes from Axim?

2024-04-23 16:48 UTC, justinhynes commented on src/containers/CourseCard/components/CourseCardImage.jsx
> +  const fallbackImageSrc = `${getConfig().LMS_BASE_URL}/theming/asset/images/no_course_image.png`;
Ah, re-reading your description now, I believe you're saying that the edX operator must provide an asset with this name for this feature to work? 

I'm a little nervous that this feature would be a bit hard to discover. I think it would be better for operators if there were some standard, placeholder images available in edx-platform that we're referencing.

2024-04-23 16:58 UTC, justinhynes requested changes
Blocking momentarily while it is determined if we need further feedback from Axim product folks.

2024-04-23 20:05 UTC, mphilbrick211 commented
> Hi @mphilbrick211 -- Is this something that would need product eyes from Axim?

Thanks for flagging, @justinhynes - will check with Jenna now.

2024-04-24 17:04 UTC, jmakowski1123 commented
This is a good fix, thanks! Will this default image work for any instance? I noted you mentioned it works with the indigo theme, will it work for anyone using tutor? 

This has product approval.

2024-05-02 04:57 UTC, hinakhadim commented
> @hinakhadim What is the behavior if the asset doesn't exist in an alternate theme? Does it fallback to the current behavior (showing a broken image?) or something worse (hopefully not an error?)

Yes, it fallback to the current behavior (showing a broken image). I've tested with image not existing then it didn't throw error and showed the current behavior.

2024-05-02 15:56 UTC, arbrandes requested changes

2024-05-02 15:56 UTC, arbrandes commented on src/containers/CourseCard/components/CourseCardImage.jsx
> +  const fallbackImageSrc = `${getConfig().LMS_BASE_URL}/theming/asset/images/no_course_image.png`;
There is precedent for hosting a filler image in the MFE itself in case of absence:

* https://github.com/openedx/frontend-app-learner-dashboard/blob/d3779adfde5be54cb135424723dd4c5a5620a0f5/src/containers/CoursesPanel/NoCoursesView/index.jsx#L7

I'm not saying I prefer this, architecturally speaking, but it would be a more immediate fix than adding placeholder images to edx-platform.

Also, I don't think hard-cording a reference to an image that needs to be provided as part of a comprehensive theme (something that's likely going away in the future), is the right thing to do here.  If we're hard-coding something, it needs to be part of the vanilla edx-platform theme.

2024-05-08 12:15 UTC, hinakhadim commented
@arbrandes  agree to your point. 
```javascript
import emptyCourseSVG from 'assets/empty-course.svg'; 
```

This image is looking weird to fix the broken image.
![image (2)](https://github.com/openedx/frontend-app-learner-dashboard/assets/112946189/86cd8bda-eab3-4b9f-89ae-96fa3c394ffd)

If you can share other alternative, then i'll really appreciate it.

2024-05-09 12:20 UTC, arbrandes commented
> If you can share other alternative, then i'll really appreciate it.

Apologies, I didn't mean to say we should use _that_ image.  We'll need to create a new one that works for this use case.

2024-05-10 12:53 UTC, hinakhadim commented
Sure. Can you please mention the team who will take care of this?

2024-05-15 15:58 UTC, arbrandes commented
Good question.  I guess I was expecting you'd be able to submit the one in Indigo here, but of course, that is presuming a lot. :)

If that's not the case, then it's just something we'll have to add to the community backlog for somebody to pick up (including, possibly, Axim itself, but I can't promise we'll have the capacity soon).

2024-05-17 06:00 UTC, hinakhadim commented
> Good question. I guess I was expecting you'd be able to submit the one in Indigo here, but of course, that is presuming a lot. :)
> 
> If that's not the case, then it's just something we'll have to add to the community backlog for somebody to pick up (including, possibly, Axim itself, but I can't promise we'll have the capacity soon).

We have included [this](https://github.com/overhangio/tutor-indigo/blob/master/tutorindigo/templates/indigo/lms/static/images/no_course_image.png) image in indigo theme and add its link here in `fallbackImgSrc` variable. I know it makes us dependent on edx-platform but user can replace that image from theme and can use his own image (user is not restricted) .  
Other option is that we can include that image here in this MFE and import it like `import FallbackCourseImg from 'assets/no_course_img.png';`. But, in this user must has to use that image (user is restricted). Otherwise, he has to change image by forking this repo. I am thinking from this perspective.

What are your thoughts on this regarding architecture considering future updates in LMS and MFE and user independence? (As studio/CMS also moved to MFE)

2024-05-17 16:23 UTC, arbrandes commented
> Other option is that we can include that image here in this MFE and import it like import FallbackCourseImg from 'assets/no_course_img.png';. But, in this user must has to use that image (user is restricted). Otherwise, he has to change image by forking this repo. I am thinking from this perspective.

Good point.  This means we should make the image overridable via [brand-openedx](https://github.com/openedx/brand-openedx), or, as mentioned earlier, we make the image available as part of the default Open edX theme in edx-platform, so that users don't have to have indigo installed for this to work.

I prefer the first option, as it decouples the UI from the backend a little bit more.  But it would be best if the image were provided as an SVG, as opposed to a PNG, if at all possible.

2024-05-21 06:34 UTC, hinakhadim commented
Awesome. Including image in [brand-openedx](https://github.com/openedx/brand-openedx) seems the best option because users can fork brand-openedx for image replacement instead of learner-dashboard mfe. I am able to include `png` image and that is working fine. If I import `svg` image, I am getting the following error:

```bash
Module not found: Can't resolve 'react' in '/openedx/brand-openedx/paragon/images'
brand-openedx/paragon/images/no_course_image.svg
```

2024-05-21 16:14 UTC, jsnwesson commented
@hinakhadim unless I'm misunderstanding how `brand-openedx` is being used here, I don't see an SVG version of `no_course_image` in the repo, so that might explain why it's failing to import? https://github.com/openedx/brand-openedx/tree/master/paragon/images

2024-05-22 06:37 UTC, hinakhadim commented
> @hinakhadim unless I'm misunderstanding how `brand-openedx` is being used here, I don't see an SVG version of `no_course_image` in the repo, so that might explain why it's failing to import? https://github.com/openedx/brand-openedx/tree/master/paragon/images

@jsnwesson I added that image in cloned brand-openedx (one in png format and one in svg format). I then use that brand-openedx using `module.config.js`. I imported that image in `learner-dashboard` as:

```javascript
import FallbackImageSrc from '@edx/brand/paragon/images/no_course_image.png';

// use it like

<img
        className="pgn__card-image-cap show"
        src={!hasImageError ? bannerImgSrc : FallbackImageSrc}
        alt={formatMessage(messages.bannerAlt)}
        onError={() => {
          if (!hasImageError) { setHasImageError(true); }
        }}
/>
```

The above works fine and loaded the image. But when I try to use `.svg` image, I got the error `Module not found: Can't resolve 'react' in '/openedx/brand-openedx/paragon/images'`. I tried importing svg image like this:

```javascript
import FallbackImageSrc from '@edx/brand/paragon/images/no_course_image.svg';
import * as FallbackImageSrc from '@edx/brand/paragon/images/no_course_image.svg';
```

2025-04-14 15:33 UTC, justinhynes commented
Hi @hinakhadim, is this still PR still under active development? If not, can we close it? I don't believe we've seen any recent movement on it and just wanted to check in. 

Thanks!

2025-04-15 01:51 UTC, closed without merging