fix: replace the header with openedx header
openedx/frontend-app-learner-dashboard pull request #327
Opened 2024-04-26 06:34 UTC by ahtesham-quraish

Description:
Replace the custom header with Openedx header and prepare the header the menu

Jira Ticket
[VAN-1914](https://2u-internal.atlassian.net/browse/VAN-1914)

How this has been tested?
- It has been tested locally
- New unit test is added to cover the menu feature

| Before | After |
| ------------- | ------------- |
|![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/12580995/73b1c06d-759c-4730-8852-355ae23c6c5c) | ![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/12580995/d785eb10-496f-4b99-8f76-c8d9322a0fa9)|

2024-04-26 07:29 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +      content: formatMessage(messages.course),
this should be active. no?

2024-04-26 07:29 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +    },
i see an onClick implemented in the learner-dashboard's custom header on this menu item. Whats the purpose of that onClick? is it okay to remove that or should we do something about it?

2024-04-26 07:29 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +  userMenu: [
Do we need authenticated user check here? as in AuthenticatedUserDropdown?

2024-04-26 07:29 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +          ...(!_.isEmpty(dashboard) ? [{
is it same as `!!dashboard`?

2024-04-26 07:29 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +        }] : []),
i see career link before profile in AuthenticatedUserDropdown.jsx

2024-04-26 07:29 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +          content: formatMessage(messages.career),
we are not providing a label as https://github.com/openedx/frontend-app-learner-dashboard/blob/master/src/containers/LearnerDashboardHeader/ExpandedHeader/AuthenticatedUserDropdown.jsx#L50-L52

2024-04-26 07:29 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +          onClick: () => {
would this onClick work? do we have such support on configurable header?

2024-04-26 07:29 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/index.jsx
> +    learnerHomeHeaderMenu = useLearnerDashboardHeaderMenu({ courseSearchUrl, authenticatedUser, dashboard });
please format this

2024-04-26 07:29 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/index.test.jsx
> -    expect(wrapper.instance.findByType('ExpandedHeader')).toHaveLength(1);
can we instead add expectation for component header?

2024-04-26 07:33 UTC, ahtesham-quraish commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +      content: formatMessage(messages.course),
done

2024-04-26 07:40 UTC, ahtesham-quraish commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +  userMenu: [
do we need it i am just thinking what do you think? is there any case where this check would helpful?

2024-04-26 07:41 UTC, ahtesham-quraish commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +          ...(!_.isEmpty(dashboard) ? [{
I have tried it but it was not working because i was getting empty object and this !!dashboard returning me true which is wrong

2024-04-26 07:42 UTC, ahtesham-quraish commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +        }] : []),
i changed it thanks

2024-04-26 07:51 UTC, ahtesham-quraish commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.js
> +          content: formatMessage(messages.career),
Done

2024-04-26 07:56 UTC, ahtesham-quraish commented on src/containers/LearnerDashboardHeader/index.test.jsx
> -    expect(wrapper.instance.findByType('ExpandedHeader')).toHaveLength(1);
it won't create any difference because the tests that are written before are just snapshots tests so we don't need this

2024-05-14 07:16 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.jsx
> +          ...(!_.isEmpty(dashboard) ? [{
i think we should keep the condition same as it is in learner-dashboard `!!dashboard`.

2024-05-14 07:53 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.jsx
> +          ...(!_.isEmpty(dashboard) ? [{
I will let the relevant team comment on this.

2024-05-14 07:53 UTC, syedsajjadkazmii approved these changes

2024-05-14 21:11 UTC, jsnwesson commented
Hey @ahtesham-quraish , I'll be looking over this PR tomorrow! A question that I do have is whether it's possible to move the edX logic of `LearnerDashboardMenu.jsx` to the forked Header repo (`frontend-component-header-edx`), which I think would help with really bringing Learner Dashboard closer to how the Header component is implemented across the MFEs.

2024-05-15 12:47 UTC, arbrandes requested changes
This is great in general - thanks!  I'd like to see some of the business-specific code moved elsewhere, though, if we can manage it.

2024-05-15 12:47 UTC, arbrandes commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.jsx
> +    ...(getConfig().ENABLE_EDX_PERSONAL_DASHBOARD ? [
Ideally, this should be moved somewhere else.  We can either put the header behind a `<PluginSlot />` so this 2U-specific can go in a plugin, or, as @jsnwesson comments, this could move to `frontend-component-header-edx`.

2024-05-15 12:47 UTC, arbrandes commented on src/containers/LearnerDashboardHeader/LearnerDashboardMenu.jsx
> +        ...(_.isEmpty(dashboard) && getConfig().CAREER_LINK_URL ? [{
This also looks like org-specific code that we could take this opportunity to move to a plugin or a header fork.

2024-05-16 06:22 UTC, ahtesham-quraish commented
We were going with feature parity but after looking at the @arbrandes comment we are going to see the strategy to remove the 2u specific code from Dashboard MFE and move it in header-edx fork so that is why we are holding this PR back.

2024-05-29 09:01 UTC, syedsajjadkazmii commented
> This is great in general - thanks! I'd like to see some of the business-specific code moved elsewhere, though, if we can manage it.

Hi @arbrandes, Thanks. We have removed the business-specific code from the PR. that code will be added through plugin slots in header. Updated the PR description as well.

2024-07-03 16:43 UTC, jsnwesson commented on src/containers/LearnerDashboardHeader/hooks.js
> +  return getLearnerHeaderMenu(formatMessage, courseSearchUrl, authenticatedUser, dashboard, exploreCoursesClick);
I'm noticing that `dashboard` never gets used by `getLearnerHeaderMenu`, and it's supposed to be data from `reduxHooks.useEnterpriseDashboardData()` in `LearnerDashboardHeader/index.jsx`. Should some of this logic live in the 2U-forked header-component?

2024-07-31 04:26 UTC, syedsajjadkazmii commented on src/containers/LearnerDashboardHeader/hooks.js
> +  return getLearnerHeaderMenu(formatMessage, courseSearchUrl, authenticatedUser, dashboard, exploreCoursesClick);
yes, you are right. The `dashboard` is removed from here and edx specific login has been moved out.

2024-08-05 09:17 UTC, syedsajjadkazmii commented
Hi @jsnwesson @arbrandes,

this PR is ready for re-review. Please have a look.

2024-08-06 21:50 UTC, jsnwesson commented
Thanks @syedsajjadkazmii ! I tested out the Learner Dashboard locally with the other PRs you linked above, and this checks out for me.

2024-08-09 20:22 UTC, arbrandes approved these changes
I've (finally) tested this, and it works fine!  Code looks good, too.  Thanks a lot for doing this!

2024-08-09 20:23 UTC, arbrandes commented
@brian-smith-tcril, FYI: learner dashboard will now have a standard header, which should make the slot work a little easier.

2024-08-12 06:55 UTC, merged