feat: add plugin slot for course card action
openedx/frontend-app-learner-dashboard pull request #464
Opened 2024-09-25 18:54 UTC by jsnwesson

This PR makes the first step toward removing the Upgrade Button from Learner Dashboard's core functionality, by creating a `CourseCardActionSlot` whose default component is the Upgrade Button. A follow up PR will remove the default component entirely, as well as remove the source code itself. 

To test this locally: 
1. Pull down this branch into your local environment
2. In the `env.config.js` file in your root directory, add the following configuration. To toggle the default component, you can adjust the `keepDefault`.
```
import { DIRECT_PLUGIN, PLUGIN_OPERATIONS } from '@openedx/frontend-plugin-framework';

const config = {
  pluginSlots: {
    course_card_action_slot: {
      keepDefault: false,
      plugins: [
        {
          // Insert custom content after course card buttons
          op: PLUGIN_OPERATIONS.Insert,
          widget: {
            id: 'custom_course_card_action',
            priority: 60,
            type: DIRECT_PLUGIN,
            RenderWidget: ({cardId}) => (
              <div>
                <p>📚: {cardId}</p>
              </div>
            ),
          },
        },
      ]
    }
  },
}

export default config;
```

Contributes to: #438 #297

2024-09-25 19:36 UTC, MaxFrank13 approved these changes
Just a couple nit picks. Thanks for setting this one up!

2024-09-25 19:36 UTC, MaxFrank13 commented on src/containers/CourseCard/components/CourseCardActions/index.jsx
> +import CourseCardActionSlot from '../../../../plugin-slots/CourseCardActionSlot';
Nit: this can actually be imported like so:

```suggestion
import CourseCardActionSlot from 'plugin-slots/CourseCardActionSlot';
```
I'll admit I don't know exactly how this works though. It doesn't work for all MFEs so it must have something to do with the way LD is set up 🤷

2024-09-25 19:36 UTC, MaxFrank13 commented on src/plugin-slots/CourseCardActionSlot/index.jsx
> +import UpgradeButton from '../../containers/CourseCard/components/CourseCardActions/UpgradeButton';
Nit: same as above
```suggestion
import UpgradeButton from 'containers/CourseCard/components/CourseCardActions/UpgradeButton';
```

2024-09-26 14:01 UTC, arbrandes requested changes

2024-09-26 14:01 UTC, arbrandes commented on src/plugin-slots/CourseCardActionSlot/index.jsx
> +  } = reduxHooks.useCardEnrollmentData(cardId);
I'd like to do a little back-and-forth on these three course properties, and how to best handle them for this slot.

On the one hand, it makes sense for content in the slot to have access to certain course props without having to query the server.  I'm also generally of the opinion that if we expect the content to actually have access to these, they should be passed in as slot props and thus become part of the supported API.

On the other, we should be getting rid of variables such as `isExecEd2UCourse` entirely, and I would be very much against making that one an explicitly supported API.

In this case it might be best if - at least for the latter variable - the plugin content itself should reach into the context to fish out `isExecEd2UCourse`.  Not sure.  Thoughts?

2024-09-26 17:43 UTC, arbrandes approved these changes
As per the conversation in today's FWG meeting, this is fine for now.

2024-09-26 17:43 UTC, arbrandes commented on src/plugin-slots/CourseCardActionSlot/index.jsx
> +  } = reduxHooks.useCardEnrollmentData(cardId);
For the record, we discussed this in today's FWG.  Summary here: https://openedx.atlassian.net/wiki/spaces/COMM/pages/4504518657

2024-09-26 18:41 UTC, brian-smith-tcril approved these changes

2024-09-26 23:01 UTC, jsnwesson commented
@sarina here's some screenshots, which I actually liked the custom button example so much that _that's_ what is now going into the repo documentation for this plugin slot!

2024-09-27 15:11 UTC, brian-smith-tcril commented on src/plugin-slots/CourseCardActionSlot/README.md
> +```
This example looks wonderful now! Super pretty.

Would you mind updating one of the buttons to include something about the `cardId`? One thing I really liked about the example you had before was that it demonstrated the `pluginProps` being used.

2024-09-27 16:58 UTC, sarina commented
Thank you this is perfect!

2024-09-27 17:26 UTC, jsnwesson commented on src/plugin-slots/CourseCardActionSlot/README.md
> +```
Good idea, I sure can!

2024-10-21 19:01 UTC, merged

2026-02-02 16:34 UTC, Cup0fCoffee commented
@jsnwesson @arbrandes @sarina Hi guys, I wanted to ask - is there a reason the default action buttons ([these](https://github.com/openedx/frontend-app-learner-dashboard/blob/master/src/containers/CourseCard/components/CourseCardActions/index.jsx#L24-L34)) were not included as children of the slot? Currently, this slot can be used to add new custom action items, but not to customize the default ones, which is desired in some situations and would be nice without having to redefine the entire CourseCard or even CourseList. Is there stopping us from making the change and upstreaming it? The change seems trivial to me (the most complex part would probably be updating the tests). And as far as I can tell, the change won't affect user experience, so I would assume no product proposal would be necessary, right?

2026-02-12 19:21 UTC, arbrandes commented
@Cup0fCoffee, good question.  I guess it's ultimately a question for product: do we want to allow people to override those buttons?

I don't have a strong opinion either way.  @brian-smith-tcril?

2026-02-17 16:01 UTC, brian-smith-tcril commented
I'd be open to adding the primary action to the slot, but I'd want to make sure we handle the use case of *not* replacing the primary action button well.

2 possible options come to mind:

1. Create a new slot for *just* the primary action. The existing slot doesn't change.
2. Create a new slot for both primary and secondary action. Move the existing conditional primary action button logic (displaying `ViewCourseButton`/`SelectSessionButton`/`ResumeButton`/`BeginCourseButton` based on `isEntitlement`/`isFulfilled`/`isArchived`/`hasStarted`) into a new `CourseCardPrimaryAction` component that plugin authors can include in their plugins. Then have the new slot be `<NewSlot><OldSlot /><CourseCardPrimaryAction /></NewSlot>`

Both of those options ensure:
* The existing slot continues to work (plugin authors don't need to make new plugins if they're currently using the existing slot)
* The new slot supports *not* changing the primary action well.

2026-02-18 10:54 UTC, arbrandes commented
My hunch is that option 1 would the simplest: just add a new slot for the primary button(s).

2026-02-18 22:30 UTC, Cup0fCoffee commented
@brian-smith-tcril @arbrandes Thank you both for responding! I'll follow up with the client to see if they are still interested in pursuing this.