fix: display programs only if the url is configured
openedx/frontend-app-learner-dashboard pull request #479
Opened 2024-10-18 13:39 UTC by dcoa

2024-10-22 17:12 UTC, arbrandes requested changes
I reviewed the code and I think the approach makes total sense.  It hits a generic django-config-models table that is automatically cached, so it shouldn't be a performance problem.

I also tested it and it works perfectly.  Congrats!

It would be better to pass the coverage CI tests, though, as noted in a review comment.

2024-10-22 17:12 UTC, arbrandes commented on src/hooks/api.js
> +        setConfig(data);
If you manage to get test coverage on this line (it shouldn't be too hard, maybe by mocking `getProgramsConfig`), we can fix the CI failure.

2024-10-22 20:27 UTC, jsnwesson commented on src/hooks/api.js
> +        setConfig(data);
++ to getting this covered!

2024-10-22 21:22 UTC, jsnwesson commented
I can confirm that this PR still allows me to see "Programs" in my hosted devstack! @arbrandes I have no objections, as long as some test coverage can be added in the `api.js` file, as you mentioned. 

<img width="1034" alt="Screenshot 2024-10-22 at 2 21 09 PM" src="https://github.com/user-attachments/assets/6c96e370-3c91-40d4-8eed-a7dc3cc84ce8">

2024-10-22 21:40 UTC, jsnwesson approved these changes

2024-10-24 22:34 UTC, dcoa commented
@arbrandes @jsnwesson , thank you for reviewing this PR, I covered the lines in the api hook file.

2024-10-25 15:22 UTC, arbrandes requested changes
Still requires a couple of changes.  Thanks, though!

2024-10-25 15:22 UTC, arbrandes commented on src/hooks/api.js
> +        setConfig(data);
It seems this line is still uncovered, @dcoa.

2024-10-25 15:22 UTC, arbrandes commented on src/hooks/api.js
> +        console.error('Error accessing programs configuration', error);
Also, I'm not a huge fan of leaving `console()` calls in production code.  It would be better to remove it.

2024-10-25 15:50 UTC, jsnwesson commented on src/hooks/api.js
> +        console.error('Error accessing programs configuration', error);
Out of curiosity, what would your thoughts be on using a `log.Error` from [frontend-platform](https://github.com/openedx/frontend-platform/blob/a0eea63b45f6937c40b542b047ff7908629b4cf8/src/logging/interface.js#L70), since this error would be useful to capture for anyone with a logging service?

2024-10-29 01:19 UTC, dcoa commented on src/hooks/api.js
> +        console.error('Error accessing programs configuration', error);
@jsnwesson  you are right I should use the logError from frontend-platoform? Do you think like that is okay or just passing the error is enough?

2024-10-29 19:58 UTC, dcoa commented on src/hooks/api.js
> +        setConfig(data);
@arbrandes it is covered now :)

2024-11-13 04:40 UTC, dcoa commented
@arbrandes, do you thing there is any additional change here to be addressed?

2024-11-18 14:49 UTC, arbrandes commented on src/hooks/api.js
> +        console.error('Error accessing programs configuration', error);
@jsnwesson, yeah, `log.Error` is a much better way to handle it.

2024-11-18 14:51 UTC, merged

2024-11-18 14:52 UTC, arbrandes commented
@dcoa, do you mind creating a backport of this to the sumac.master branch?

2024-11-18 19:37 UTC, deborahgu commented
@dcoa @arbrandes 

I'm going to roll this back, it is broken in a live (ie. non-tutor, non-devstack) environment. The code determines if programs is active by `baseAppUrl('/config/programs');`.  [The URL is permissioned](https://github.com/openedx/django-config-models/blob/32c885d92131fcac1680c518c6f8a127a67f5e2e/config_models/views.py#L42-L52) and is inaccessible  under production circumstances. This will need another method. Possibilities: a URL that's reachable by any logged in user, or a server-side check, or looking to see if this is exposed via a standard config setting. (That last would be ideal.)