Product interview sidebar
openedx/frontend-app-learner-dashboard pull request #75
Opened 2022-11-28 14:21 UTC by Zacharis278

### [MST-1703](https://2u-internal.atlassian.net/browse/MST-1703)

Add widget for scheduling product team interviews

2022-11-28 14:42 UTC, alangsto approved these changes
👍

2022-11-30 15:53 UTC, mattcarter approved these changes
approved

2022-12-14 16:10 UTC, wittjeff requested changes

2022-12-14 16:10 UTC, wittjeff commented on src/containers/WidgetContainers/LoadedSidebar/index.jsx
>    <div className="widget-sidebar">
Can you make this an <aside>?

2024-01-08 20:07 UTC, justinhynes commented
Hi @Zacharis278!

I'm trying to check up on some open PRs for this repo. Is this change still needed? If not, may I close it? If so, could you address the open requests and fix the conflicts on the PR? 

Thanks in advance!

2024-01-08 20:10 UTC, Zacharis278 commented
@justinhynes releasing this was put on hold by the product team so it's fallen way behind main. I'll have to check in on if/when this can actually be merged and get back to you.

2024-02-02 19:34 UTC, justinhynes commented
Considering this is over a year old without much movement, I'm going to close this PR. Please resubmit a PR if this becomes a priority again. Thanks!

2024-02-02 19:34 UTC, closed without merging